const countriesList = [
  { codecountry: "ad", country: "Andorra" },
  {
    codecountry: "ae",
    country: "Emiratos Árabes Unidos",
  },
  { codecountry: "af", country: "Afganistán" },
  {
    codecountry: "ag",
    country: "Antigua y Barbuda",
  },
  { codecountry: "ai", country: "Anguila" },
  { codecountry: "al", country: "Albania" },
  { codecountry: "am", country: "Armenia" },
  { codecountry: "ao", country: "Angola" },
  { codecountry: "aq", country: "Antártida" },
  { codecountry: "ar", country: "Argentina" },
  { codecountry: "as", country: "Samoa Americana" },
  { codecountry: "at", country: "Austria" },
  { codecountry: "au", country: "Australia" },
  { codecountry: "aw", country: "Aruba" },
  { codecountry: "ax", country: "Åland" },
  { codecountry: "az", country: "Azerbaiyán" },
  {
    codecountry: "ba",
    country: "Bosnia y Herzegovina",
  },
  { codecountry: "bb", country: "Barbados" },
  { codecountry: "bd", country: "Bangladesh" },
  { codecountry: "be", country: "Bélgica" },
  { codecountry: "bf", country: "Burkina Faso" },
  { codecountry: "bg", country: "Bulgaria" },
  { codecountry: "bh", country: "Baréin" },
  { codecountry: "bi", country: "Burundi" },
  { codecountry: "bj", country: "Benín" },
  { codecountry: "bl", country: "San Bartolomé" },
  { codecountry: "bm", country: "Bermudas" },
  { codecountry: "bn", country: "Brunéi" },
  { codecountry: "bo", country: "Bolivia" },
  {
    codecountry: "bq",
    country: "Caribe Neerlandés",
  },
  { codecountry: "br", country: "Brasil" },
  { codecountry: "bs", country: "Bahamas" },
  { codecountry: "bt", country: "Bután" },
  { codecountry: "bv", country: "Isla Bouvet" },
  { codecountry: "bw", country: "Botsuana" },
  { codecountry: "by", country: "Bielorrusia" },
  { codecountry: "bz", country: "Belice" },
  { codecountry: "ca", country: "Canadá" },
  { codecountry: "cc", country: "Islas Cocos" },
  {
    codecountry: "cd",
    country: "Congo (Rep. Dem.)",
  },
  {
    codecountry: "cf",
    country: "República Centroafricana",
  },
  { codecountry: "cg", country: "Congo" },
  { codecountry: "ch", country: "Suiza" },
  { codecountry: "ci", country: "Costa de Marfil" },
  { codecountry: "ck", country: "Islas Cook" },
  { codecountry: "cl", country: "Chile" },
  { codecountry: "cm", country: "Camerún" },
  { codecountry: "cn", country: "China" },
  { codecountry: "co", country: "Colombia" },
  { codecountry: "cr", country: "Costa Rica" },
  { codecountry: "cu", country: "Cuba" },
  { codecountry: "cv", country: "Cabo Verde" },
  { codecountry: "cw", country: "Curazao" },
  { codecountry: "cx", country: "Isla de Navidad" },
  { codecountry: "cy", country: "Chipre" },
  { codecountry: "cz", country: "República Checa" },
  { codecountry: "de", country: "Alemania" },
  { codecountry: "dj", country: "Yibuti" },
  { codecountry: "dk", country: "Dinamarca" },
  { codecountry: "dm", country: "Dominica" },
  {
    codecountry: "do",
    country: "República Dominicana",
  },
  { codecountry: "dz", country: "Argelia" },
  { codecountry: "ec", country: "Ecuador" },
  { codecountry: "ee", country: "Estonia" },
  { codecountry: "eg", country: "Egipto" },
  {
    codecountry: "eh",
    country: "Sahara Occidental",
  },
  { codecountry: "er", country: "Eritrea" },
  { codecountry: "es", country: "España" },
  { codecountry: "et", country: "Etiopía" },
  { codecountry: "eu", country: "Unión Europea" },
  { codecountry: "fi", country: "Finlandia" },
  { codecountry: "fj", country: "Fiyi" },
  { codecountry: "fk", country: "Islas Malvinas" },
  { codecountry: "fm", country: "Micronesia" },
  { codecountry: "fo", country: "Islas Feroe" },
  { codecountry: "fr", country: "Francia" },
  { codecountry: "ga", country: "Gabón" },
  { codecountry: "gb", country: "Reino Unido" },
  { codecountry: "gb-eng", country: "Inglaterra" },
  {
    codecountry: "gb-nir",
    country: "Irlanda del Norte",
  },
  { codecountry: "gb-sct", country: "Escocia" },
  { codecountry: "gb-wls", country: "Gales" },
  { codecountry: "gd", country: "Granada" },
  { codecountry: "ge", country: "Georgia" },
  {
    codecountry: "gf",
    country: "Guayana Francesa",
  },
  { codecountry: "gg", country: "Guernsey" },
  { codecountry: "gh", country: "Ghana" },
  { codecountry: "gi", country: "Gibraltar" },
  { codecountry: "gl", country: "Groenlandia" },
  { codecountry: "gm", country: "Gambia" },
  { codecountry: "gn", country: "Guinea" },
  { codecountry: "gp", country: "Guadalupe" },
  {
    codecountry: "gq",
    country: "Guinea Ecuatorial",
  },
  { codecountry: "gr", country: "Grecia" },
  {
    codecountry: "gs",
    country: "Islas Georgias del Sur y Sándwich del Sur",
  },
  { codecountry: "gt", country: "Guatemala" },
  { codecountry: "gu", country: "Guam" },
  { codecountry: "gw", country: "Guinea-Bisáu" },
  { codecountry: "gy", country: "Guyana" },
  { codecountry: "hk", country: "Hong Kong" },
  {
    codecountry: "hm",
    country: "Islas Heard y McDonald",
  },
  { codecountry: "hn", country: "Honduras" },
  { codecountry: "hr", country: "Croacia" },
  { codecountry: "ht", country: "Haití" },
  { codecountry: "hu", country: "Hungría" },
  { codecountry: "id", country: "Indonesia" },
  { codecountry: "ie", country: "Irlanda" },
  { codecountry: "il", country: "Israel" },
  { codecountry: "im", country: "Isla de Man" },
  { codecountry: "in", country: "India" },
  {
    codecountry: "io",
    country: "Territorio Británico del Océano Índico",
  },
  { codecountry: "iq", country: "Irak" },
  { codecountry: "ir", country: "Irán" },
  { codecountry: "is", country: "Islandia" },
  { codecountry: "it", country: "Italia" },
  { codecountry: "je", country: "Jersey" },
  { codecountry: "jm", country: "Jamaica" },
  { codecountry: "jo", country: "Jordania" },
  { codecountry: "jp", country: "Japón" },
  { codecountry: "ke", country: "Kenia" },
  { codecountry: "kg", country: "Kirguistán" },
  { codecountry: "kh", country: "Camboya" },
  { codecountry: "ki", country: "Kiribati" },
  { codecountry: "km", country: "Comoras" },
  {
    codecountry: "kn",
    country: "San Cristóbal y Nieves",
  },
  { codecountry: "kp", country: "Corea del Norte" },
  { codecountry: "kr", country: "Corea del Sur" },
  { codecountry: "kw", country: "Kuwait" },
  { codecountry: "ky", country: "Islas Caimán" },
  { codecountry: "kz", country: "Kazajistán" },
  { codecountry: "la", country: "Laos" },
  { codecountry: "lb", country: "Líbano" },
  { codecountry: "lc", country: "Santa Lucía" },
  { codecountry: "li", country: "Liechtenstein" },
  { codecountry: "lk", country: "Sri Lanka" },
  { codecountry: "lr", country: "Liberia" },
  { codecountry: "ls", country: "Lesoto" },
  { codecountry: "lt", country: "Lituania" },
  { codecountry: "lu", country: "Luxemburgo" },
  { codecountry: "lv", country: "Letonia" },
  { codecountry: "ly", country: "Libia" },
  { codecountry: "ma", country: "Marruecos" },
  { codecountry: "mc", country: "Mónaco" },
  { codecountry: "md", country: "Moldavia" },
  { codecountry: "me", country: "Montenegro" },
  {
    codecountry: "mf",
    country: "San Martín (Francia)",
  },
  { codecountry: "mg", country: "Madagascar" },
  { codecountry: "mh", country: "Islas Marshall" },
  {
    codecountry: "mk",
    country: "Macedonia del Norte",
  },
  { codecountry: "ml", country: "Malí" },
  { codecountry: "mm", country: "Myanmar" },
  { codecountry: "mn", country: "Mongolia" },
  { codecountry: "mo", country: "Macao" },
  {
    codecountry: "mp",
    country: "Islas Marianas del Norte",
  },
  { codecountry: "mq", country: "Martinica" },
  { codecountry: "mr", country: "Mauritania" },
  { codecountry: "ms", country: "Montserrat" },
  { codecountry: "mt", country: "Malta" },
  { codecountry: "mu", country: "Mauricio" },
  { codecountry: "mv", country: "Maldivas" },
  { codecountry: "mw", country: "Malawi" },
  { codecountry: "mx", country: "México" },
  { codecountry: "my", country: "Malasia" },
  { codecountry: "mz", country: "Mozambique" },
  { codecountry: "na", country: "Namibia" },
  { codecountry: "nc", country: "Nueva Caledonia" },
  { codecountry: "ne", country: "Níger" },
  { codecountry: "nf", country: "Isla Norfolk" },
  { codecountry: "ng", country: "Nigeria" },
  { codecountry: "ni", country: "Nicaragua" },
  { codecountry: "nl", country: "Países Bajos" },
  { codecountry: "no", country: "Noruega" },
  { codecountry: "np", country: "Nepal" },
  { codecountry: "nr", country: "Nauru" },
  { codecountry: "nu", country: "Niue" },
  { codecountry: "nz", country: "Nueva Zelanda" },
  { codecountry: "om", country: "Omán" },
  { codecountry: "pa", country: "Panamá" },
  { codecountry: "pe", country: "Perú" },
  {
    codecountry: "pf",
    country: "Polinesia Francesa",
  },
  {
    codecountry: "pg",
    country: "Papúa Nueva Guinea",
  },
  { codecountry: "ph", country: "Filipinas" },
  { codecountry: "pk", country: "Pakistán" },
  { codecountry: "pl", country: "Polonia" },
  {
    codecountry: "pm",
    country: "San Pedro y Miquelón",
  },
  { codecountry: "pn", country: "Islas Pitcairn" },
  { codecountry: "pr", country: "Puerto Rico" },
  { codecountry: "ps", country: "Palestina" },
  { codecountry: "pt", country: "Portugal" },
  { codecountry: "pw", country: "Palaos" },
  { codecountry: "py", country: "Paraguay" },
  { codecountry: "qa", country: "Catar" },
  { codecountry: "re", country: "Reunión" },
  { codecountry: "ro", country: "Rumania" },
  { codecountry: "rs", country: "Serbia" },
  { codecountry: "ru", country: "Rusia" },
  { codecountry: "rw", country: "Ruanda" },
  { codecountry: "sa", country: "Arabia Saudita" },
  { codecountry: "sb", country: "Islas Salomón" },
  { codecountry: "sc", country: "Seychelles" },
  { codecountry: "sd", country: "Sudán" },
  { codecountry: "se", country: "Suecia" },
  { codecountry: "sg", country: "Singapur" },
  {
    codecountry: "sh",
    country: "Santa Elena, Ascensión y Tristán de Acuña",
  },
  { codecountry: "si", country: "Eslovenia" },
  {
    codecountry: "sj",
    country: "Svalbard y Jan Mayen",
  },
  { codecountry: "sk", country: "Eslovaquia" },
  { codecountry: "sl", country: "Sierra Leona" },
  { codecountry: "sm", country: "San Marino" },
  { codecountry: "sn", country: "Senegal" },
  { codecountry: "so", country: "Somalia" },
  { codecountry: "sr", country: "Surinam" },
  { codecountry: "ss", country: "Sudán del Sur" },
  {
    codecountry: "st",
    country: "Santo Tomé y Príncipe",
  },
  { codecountry: "sv", country: "El Salvador" },
  {
    codecountry: "sx",
    country: "San Martín (Países Bajos)",
  },
  { codecountry: "sy", country: "Siria" },
  { codecountry: "sz", country: "Suazilandia" },
  {
    codecountry: "tc",
    country: "Islas Turcas y Caicos",
  },
  { codecountry: "td", country: "Chad" },
  {
    codecountry: "tf",
    country: "Tierras Australes y Antárticas Francesas",
  },
  { codecountry: "tg", country: "Togo" },
  { codecountry: "th", country: "Tailandia" },
  { codecountry: "tj", country: "Tayikistán" },
  { codecountry: "tk", country: "Tokelau" },
  { codecountry: "tl", country: "Timor Oriental" },
  { codecountry: "tm", country: "Turkmenistán" },
  { codecountry: "tn", country: "Túnez" },
  { codecountry: "to", country: "Tonga" },
  { codecountry: "tr", country: "Turquía" },
  {
    codecountry: "tt",
    country: "Trinidad y Tobago",
  },
  { codecountry: "tv", country: "Tuvalu" },
  { codecountry: "tw", country: "Taiwán" },
  { codecountry: "tz", country: "Tanzania" },
  { codecountry: "ua", country: "Ucrania" },
  { codecountry: "ug", country: "Uganda" },
  {
    codecountry: "um",
    country: "Islas Ultramarinas Menores de los Estados Unidos",
  },
  {
    codecountry: "un",
    country: "Organización de las Naciones Unidas",
  },
  { codecountry: "us", country: "Estados Unidos" },
  { codecountry: "us-ak", country: "Alaska" },
  { codecountry: "us-al", country: "Alabama" },
  { codecountry: "us-ar", country: "Arkansas" },
  { codecountry: "us-az", country: "Arizona" },
  { codecountry: "us-ca", country: "California" },
  { codecountry: "us-co", country: "Colorado" },
  { codecountry: "us-ct", country: "Connecticut" },
  { codecountry: "us-de", country: "Delaware" },
  { codecountry: "us-fl", country: "Florida" },
  { codecountry: "us-ga", country: "Georgia" },
  { codecountry: "us-hi", country: "Hawái" },
  { codecountry: "us-ia", country: "Iowa" },
  { codecountry: "us-id", country: "Idaho" },
  { codecountry: "us-il", country: "Illinois" },
  { codecountry: "us-in", country: "Indiana" },
  { codecountry: "us-ks", country: "Kansas" },
  { codecountry: "us-ky", country: "Kentucky" },
  { codecountry: "us-la", country: "Luisiana" },
  {
    codecountry: "us-ma",
    country: "Massachusetts",
  },
  { codecountry: "us-md", country: "Maryland" },
  { codecountry: "us-me", country: "Maine" },
  { codecountry: "us-mi", country: "Míchigan" },
  { codecountry: "us-mn", country: "Minnesota" },
  { codecountry: "us-mo", country: "Misuri" },
  { codecountry: "us-ms", country: "Misisipi" },
  { codecountry: "us-mt", country: "Montana" },
  {
    codecountry: "us-nc",
    country: "Carolina del Norte",
  },
  {
    codecountry: "us-nd",
    country: "Dakota del Norte",
  },
  { codecountry: "us-ne", country: "Nebraska" },
  {
    codecountry: "us-nh",
    country: "Nuevo Hampshire",
  },
  { codecountry: "us-nj", country: "Nueva Jersey" },
  { codecountry: "us-nm", country: "Nuevo México" },
  { codecountry: "us-nv", country: "Nevada" },
  { codecountry: "us-ny", country: "Nueva York" },
  { codecountry: "us-oh", country: "Ohio" },
  { codecountry: "us-ok", country: "Oklahoma" },
  { codecountry: "us-or", country: "Oregón" },
  { codecountry: "us-pa", country: "Pensilvania" },
  { codecountry: "us-ri", country: "Rhode Island" },
  {
    codecountry: "us-sc",
    country: "Carolina del Sur",
  },
  {
    codecountry: "us-sd",
    country: "Dakota del Sur",
  },
  { codecountry: "us-tn", country: "Tennessee" },
  { codecountry: "us-tx", country: "Texas" },
  { codecountry: "us-ut", country: "Utah" },
  { codecountry: "us-va", country: "Virginia" },
  { codecountry: "us-vt", country: "Vermont" },
  { codecountry: "us-wa", country: "Washington" },
  { codecountry: "us-wi", country: "Wisconsin" },
  {
    codecountry: "us-wv",
    country: "Virginia Occidental",
  },
  { codecountry: "us-wy", country: "Wyoming" },
  { codecountry: "uy", country: "Uruguay" },
  { codecountry: "uz", country: "Uzbekistán" },
  {
    codecountry: "va",
    country: "Ciudad del Vaticano",
  },
  {
    codecountry: "vc",
    country: "San Vicente y las Granadinas",
  },
  { codecountry: "ve", country: "Venezuela" },
  {
    codecountry: "vg",
    country: "Islas Vírgenes Británicas",
  },
  {
    codecountry: "vi",
    country: "Islas Vírgenes de los Estados Unidos",
  },
  { codecountry: "vn", country: "Vietnam" },
  { codecountry: "vu", country: "Vanuatu" },
  { codecountry: "wf", country: "Wallis y Futuna" },
  { codecountry: "ws", country: "Samoa" },
  { codecountry: "xk", country: "Kosovo" },
  { codecountry: "ye", country: "Yemen" },
  { codecountry: "yt", country: "Mayotte" },
  { codecountry: "za", country: "Sudáfrica" },
  { codecountry: "zm", country: "Zambia" },
  { codecountry: "zw", country: "Zimbabue" },
];
export default countriesList;
